### ISSUE TITLE
请问怎么解决Exceeded 30 redirects

### ISSUE THREAD

**Issue by 13211222** [Rlacat/jd-automask#1]
请问怎么解决Exceeded 30 redirects

**Comment by Rlacat** [comment]
有图吗

**Comment by 13211222** [comment]
![QQ图片20200208125653](https://user-images.githubusercontent.com/59818259/74079440-84070080-4a72-11ea-89e5-4c85954e3864.png)
就这样的

**Comment by Rlacat** [comment]
下载v1新版本试试。已解决。

**Comment by 13211222** [comment]
可以，辛苦了 666
