### ISSUE TITLE
对的，我昨晚重复三次左右，然后没事的时候又重复了三次，要睡觉的时候也重复三次，我也不知道什么原因，只能是相信软件，昨晚就抢到了口罩，今天继续

### ISSUE THREAD

**Issue by 13211222** [Rlacat/jd-automask#8]
> 重复把cookie删了登陆几次，我就是这样搞定的

怎么操作，直接删cookie，然后扫码登陆就好了吗？具体重复几次呢

_Originally posted by @c0ldian in https://github.com/Rlacat/jd-automask/issues/6#issuecomment-583797373_

**Comment by c0ldian** [comment]
那怎么知道已经解决了，是能成功下订单后把测试的商品ID删掉吗

**Comment by 13211222** [comment]
> 那怎么知道已经解决了，是能成功下订单后把测试的商品ID删掉吗

我也是不确定的

**Comment by 13211222** [comment]
> 那怎么知道已经解决了，是能成功下订单后把测试的商品ID删掉吗

貌似抢到了不会删除id，会继续抢，我昨天测试买有货的防毒面具，直接下了三单
